---
title: "Case_study_09"
author: "jishnu"
date: "2024-11-19"
output: html_document
---

```{r}
# Load necessary libraries
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
library(lubridate)

# Load world and US state data
data(world)
data(us_states)

#Loading the Storm Data
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)

#create new column with years >1950
new_storm_data <- storm_data %>%
  mutate(year = year(ISO_TIME)) %>%
  relocate(year, .after = ISO_TIME) %>%
  filter(year >= 1950) %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))

# Convert the data to an sf object
storms <- st_as_sf(new_storm_data, coords = c("LON", "LAT"), crs = 4326)

# Identify the bounding box of the storm data
region <- st_bbox(storms)

# Plot the world map with storm density
ggplot() +
  geom_sf(data = world) +
  facet_wrap(~decade) +
  stat_bin2d(data = storms, aes(x = st_coordinates(storms)[, 1], y = st_coordinates(storms)[, 2]), bins = 100) +
  scale_fill_distiller(palette = "YlOrRd", trans = "log", direction = -1, breaks = c(1, 10, 100, 1000)) +
   coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) +
  labs(title = "Storm Tracks per Decade", fill = "Storm Density")

# Reproject US states to match the storm data's CRS
states <- st_transform(us_states, st_crs(storms)) %>%
select(state=NAME)
  

storm_states <- st_join(storms, states, join = st_intersects, left = FALSE) %>%
group_by(state) %>%
  summarize(storms = n_distinct(NAME)) %>%
  arrange(desc(storms)) %>%
  slice(1:5) %>%
  st_drop_geometry()




```

```{r}
# Print the table
print(storm_states)

```
